### ISSUE TITLE
LastPass: Duo V4 login problems

### ISSUE THREAD

**Issue by detunized** [detunized/password-manager-access#133]
Some weird bug with Duo V4. Most likely related to the traditional/universal prompt switch and web/lib login sequence.

```
System.NullReferenceException: Object reference not set to an instance of an object.
at PasswordManagerAccess.Duo.DuoV4.ParseDeviceData(Data data)
at PasswordManagerAccess.Duo.DuoV4.GetDevices(String sessionId, RestClient rest)
at PasswordManagerAccess.Duo.DuoV4.Authenticate(String authUrl, IDuoUi ui, IRestTransport transport)
at PasswordManagerAccess.LastPass.Client.ApproveDuoWebSdkV4(String username, String url, String sessionToken, String privateToken, IUi ui, RestClient rest)
at PasswordManagerAccess.LastPass.Client.ApproveDuoWebSdk(String username, Dictionary`2 parameters, IUi ui, RestClient rest)
at PasswordManagerAccess.LastPass.Client.ApproveDuo(String username, Dictionary`2 parameters, IUi ui, RestClient rest)
at PasswordManagerAccess.LastPass.Client.ApproveOob(String username, Dictionary`2 parameters, IUi ui, RestClient rest)
at PasswordManagerAccess.LastPass.Client.LoginWithOob(String username, String password, Int32 keyIterationCount, Dictionary`2 parameters, ClientInfo clientInfo, IUi ui, RestClient rest)
at PasswordManagerAccess.LastPass.Client.Login(String username, String password, ClientInfo clientInfo, IUi ui, IRestTransport transport)
at PasswordManagerAccess.LastPass.Client.OpenVault(String username, String password, ClientInfo clientInfo, IUi ui, IRestTransport transport, ParserOptions options)
at PasswordManagerAccess.LastPass.Vault.Open(String username, String password, ClientInfo clientInfo, IUi ui, ParserOptions options)
at PasswordManagerAccess.LastPass.Vault.Open(String username, String password, ClientInfo clientInfo, IUi ui)
```

**Comment by detunized** [comment]
Seems to go away when the "Use Duo Web SDK when possible" is turned off.
