### ISSUE TITLE
LastPass/Duo: an error when using "Use Duo Web SDK when possible" setting

### ISSUE THREAD

**Issue by detunized** [detunized/password-manager-access#142]
Sometimes, when `Use Duo Web SDK when possible` is enabled, the following error is thrown:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at PasswordManagerAccess.Common.TaggedLogger.Log(LogEntry entry)
   at PasswordManagerAccess.Common.TaggedLogger.Log(String message)
   at PasswordManagerAccess.Common.RestClient.MakeRequest[TResponse,TContent](String endpoint, HttpMethod method, HttpContent content, Dictionary`2 headers, Dictionary`2 cookies, Int32 maxRedirects, TResponse allocatedResult)
   at PasswordManagerAccess.Common.RestClient.MakeRequest[TContent](String endpoint, HttpMethod method, HttpContent content, Dictionary`2 headers, Dictionary`2 cookies, Int32 maxRedirects)
   at PasswordManagerAccess.Common.RestClient.Get(String endpoint, Dictionary`2 headers, Dictionary`2 cookies, Int32 maxRedirects)
   at PasswordManagerAccess.Duo.DuoV4.GetMainHtml(String authUrl, RestClient rest)
   at PasswordManagerAccess.Duo.DuoV4.Authenticate(String authUrl, IDuoUi ui, IRestTransport transport, ISimpleLogger logger)
   at PasswordManagerAccess.LastPass.Client.ApproveDuoWebSdkV4(String username, String url, String sessionToken, String privateToken, IUi ui, RestClient rest, ISimpleLogger logger)
   at PasswordManagerAccess.LastPass.Client.ApproveDuoWebSdk(String username, Dictionary`2 parameters, IUi ui, RestClient rest, ISimpleLogger logger)
   at PasswordManagerAccess.LastPass.Client.ApproveDuo(String username, Dictionary`2 parameters, IUi ui, RestClient rest, ISimpleLogger logger)
   at PasswordManagerAccess.LastPass.Client.ApproveOob(String username, Dictionary`2 parameters, IUi ui, RestClient rest, ISimpleLogger logger)
   at PasswordManagerAccess.LastPass.Client.LoginWithOob(String username, String password, Int32 keyIterationCount, Dictionary`2 parameters, ClientInfo clientInfo, IUi ui, RestClient rest, ISimpleLogger logger)
   at PasswordManagerAccess.LastPass.Client.Login(String username, String password, ClientInfo clientInfo, IUi ui, IRestTransport transport, ISimpleLogger logger)
   at PasswordManagerAccess.LastPass.Client.OpenVault(String username, String password, ClientInfo clientInfo, IUi ui, IRestTransport transport, ParserOptions options, ISecureLogger logger)
   at PasswordManagerAccess.LastPass.Vault.Open(String username, String password, ClientInfo clientInfo, IUi ui, ParserOptions options, ISecureLogger logger)
```

**Comment by detunized** [comment]
This seems to be the logging problem
