### ISSUE TITLE
Dashlane: JSON doesn't parse

### ISSUE THREAD

**Issue by detunized** [detunized/password-manager-access#148]
```
PasswordManagerAccess.Common.InternalErrorException: Invalid JSON in response from 'https://api.dashlane.com/v1/authentication/GetAuthenticationMethodsForDevice'
---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at PasswordManagerAccess.Dashlane.Client.TryParseAuthError(RestResponse`1 response)
   --- End of inner exception stack trace ---
   at PasswordManagerAccess.Dashlane.Client.PostJson[T](String endpoint, Dictionary`2 parameters, RestClient rest)
   at PasswordManagerAccess.Dashlane.Client.RequestDeviceRegistration(String username, RestClient rest)
   at PasswordManagerAccess.Dashlane.Client.RegisterNewDeviceWithMultipleAttempts(String username, Ui ui, IRestTransport transport)
   at PasswordManagerAccess.Dashlane.Client.OpenVault(String username, Ui ui, ISecureStorage storage, IRestTransport transport)
   at PasswordManagerAccess.Dashlane.Vault.Open(String username, String password, Ui ui, ISecureStorage storage, IRestTransport transport)
   at PasswordManagerAccess.Dashlane.Vault.Open(String username, String password, Ui ui, ISecureStorage storage)
```

**Comment by detunized** [comment]
Not reproducible. Probably a glitch.
