### ISSUE TITLE
Zoho Vault fails to sign in

### ISSUE THREAD

**Issue by detunized** [detunized/password-manager-access#43]
```
Request to https://accounts.zoho.com/signin/auth failed with HTTP status 404
   at PasswordManagerAccess.ZohoVault.Client.Login(String username, String password, String token, String tld, Ui ui, ISecureStorage storage, RestClient rest) in /path/to/password-manager-access/src/ZohoVault/Client.cs:line 183
   at PasswordManagerAccess.ZohoVault.Client.OpenVault(String username, String password, String passphrase, Ui ui, ISecureStorage storage, IRestTransport transport) in /path/to/password-manager-access/src/ZohoVault/Client.cs:line 43
   at PasswordManagerAccess.ZohoVault.Vault.Open(String username, String password, String passphrase, Ui ui, ISecureStorage storage, IRestTransport transport) in /path/to/password-manager-access/src/ZohoVault/Vault.cs:line 29
   at PasswordManagerAccess.ZohoVault.Vault.Open(String username, String password, String passphrase, Ui ui, ISecureStorage storage) in /path/to/password-manager-access/src/ZohoVault/Vault.cs:line 15
   at PasswordManagerAccess.Example.ZohoVault.Program.Main(String[] args) in /path/to/password-manager-access/example/ZohoVault/Program.cs:line 78
```

**Comment by detunized** [comment]
Fixed in v7.0.0
