### ISSUE TITLE
Kaspersky: crash

### ISSUE THREAD

**Issue by detunized** [detunized/password-manager-access#47]
Crash during login

```
Request to 'https://my.kaspersky.com/?returnUrl=%2Fdashboard' failed
   at PasswordManagerAccess.Kaspersky.Client.GetXmppInfo(String authCookie, RestClient rest) in C:\password-manager-access-master\src\Kaspersky\Client.cs:line 237
   at PasswordManagerAccess.Kaspersky.Client.OpenVault(String username, String accountPassword, String vaultPassword, IRestTransport transport) in C:\password-manager-access-master\src\Kaspersky\Client.cs:line 28
   at PasswordManagerAccess.Kaspersky.Vault.Open(String username, String accountPassword, String vaultPassword, IRestTransport transport) in C:\password-manager-access-master\src\Kaspersky\Vault.cs:line 27
   at PasswordManagerAccess.Kaspersky.Vault.Open(String username, String accountPassword, String vaultPassword) in C:\password-manager-access-master\src\Kaspersky\Vault.cs:line 15
   at PasswordManagerAccess.Example.Kaspersky.Program.Main(String[] args) in C:\password-manager-access-master\example\Kaspersky\Program.cs:line 19
```

**Comment by detunized** [comment]
Looks like the protocol has changed at least in two places.

1. The request to https://my.kaspersky.com/MyPasswords from `GetXmppInfo` requires more cookies that are sent by the server during the previous steps.

2. The BOSH stuff doesn't work over HTTPS anymore and needs to be communicated over WSS. See if [ClientWebSocket](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=net-5.0) could be used.
