### ISSUE TITLE
Bitwarden RSA decryption fails

### ISSUE THREAD

**Issue by detunized** [detunized/password-manager-access#53]
Seems like the RSA parameter import fails. 

```
PasswordManagerAccess.Common.CryptoException: RSA decryption failed ---> System.Security.Cryptography.CryptographicException: Bad Data.

at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)

at System.Security.Cryptography.Utils._ImportKey(SafeProvHandle hCSP, Int32 keyNumber, CspProviderFlags flags, Object cspObject, SafeKeyHandle& hKey)

at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)

at PasswordManagerAccess.Common.Crypto.DecryptRsa(Byte[] ciphertext, RSAParameters privateKey, RSAEncryptionPadding padding)

— End of inner exception stack trace —

at PasswordManagerAccess.Common.Crypto.DecryptRsa(Byte[] ciphertext, RSAParameters privateKey, RSAEncryptionPadding padding)

at PasswordManagerAccess.Bitwarden.CipherString.DecryptRsa2048OaepSha1(Byte[] key)

at PasswordManagerAccess.Bitwarden.CipherString.Decrypt(Byte[] key)

at PasswordManagerAccess.Bitwarden.Client.<>c_DisplayClass19_0.<DecryptOrganizationKeys>b_1(Organization x)

at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)

at PasswordManagerAccess.Bitwarden.Client.DecryptOrganizationKeys(Profile profile, Byte[] privateKey)

at PasswordManagerAccess.Bitwarden.Client.DecryptVault(Vault vault, Byte[] key)

at PasswordManagerAccess.Bitwarden.Client.OpenVault(String username, String password, String deviceId, String baseUrl, IUi ui, ISecureStorage storage, IRestTransport transport)

at PasswordManagerAccess.Bitwarden.Vault.Open(String username, String password, String deviceId, String baseUrl, IUi ui, ISecureStorage storage)
```

**Comment by detunized** [comment]
There has been some logging added in the `bwrsalog` branch. This should help to log the broken private keys in a safe way without exposing the private info. This issue is still open though.

**Comment by detunized** [comment]
The issue was caused by some RSA keys that have some of the components too short. Usually one byte shorter. They had to be left-padded with zeros to the expected length. .NET Framework 4+ is very fussy about that one. .NET Core (Mac/Linux) seems to be accepting these keys no problem. From the experiments it seems the problem comes from a small minority of keys generated by OpenSSL (1.5%). On average 15 keys from the following set would have this problem:

```bash
for i in `seq 0 999`; do openssl genrsa -out $i.key 2048; done
```

The keys generated by by .NET itself do not have this problem.
