### ISSUE TITLE
LastPass: lastpass.eu support

### ISSUE THREAD

**Issue by detunized** [detunized/password-manager-access#68]
The login fails when the data storage location is moved to lastpass.eu

```
PasswordManagerAccess.Common.InternalErrorException: Please update to the latest version of LastPass.
   at PasswordManagerAccess.LastPass.Client.Login(String username, String password, ClientInfo clientInfo, IUi ui, RestClient rest)
   at PasswordManagerAccess.LastPass.Client.OpenVault(String username, String password, ClientInfo clientInfo, IUi ui, IRestTransport transport)
   at PasswordManagerAccess.LastPass.Vault.Open(String username, String password, ClientInfo clientInfo, IUi ui)
```

**Comment by detunized** [comment]
A request is submitted to the LP support to move one of the test accounts to the EU data center. Waiting for the confirmation.
