### ISSUE TITLE
1Password: add RSA-OAEP-256 support

### ISSUE THREAD

**Issue by detunized** [detunized/password-manager-access#99]
Currently we don't support it and get the following:

```
PasswordManagerAccess.Common.UnsupportedFeatureException: Encryption scheme 'RSA-OAEP-256' is not supported
   at PasswordManagerAccess.OnePassword.Keychain.CanDecrypt(String scheme, String keyId)
   at PasswordManagerAccess.OnePassword.Client.FindWorkingKey(VaultAccessInfo[] accessList, Keychain keychain)
   at PasswordManagerAccess.OnePassword.Client.<>c__DisplayClass37_0.<GetAccessibleVaults>b__0(VaultInfo vault)
```

Need to figure out how to reproduce this.

**Comment by detunized** [comment]
It's non trivial to create a vault like that. The code could be changed in the DevTools debugger. See the following and patch the arguments to `generateKey`:

```js
return t = ["encrypt", "decrypt"],
n = f.HZ.DEFAULT_ALG,
r = e || u.generateUUID(),
[4, u.crypto.subtle.generateKey(n, !0, t)];
```

It seems `RSACryptoServiceProvider` doesn't support SHA256. Need to use `RSACng` or `RSAOpenSsl` depending on the platform.
